#!/usr/bin/env node
/**
 * Writes packages/shared/src/abi.ts from the compiled Hardhat artifacts, so the backend and the
 * frontend always use the exact ABIs of the deployed contracts.
 * Run after `hardhat compile`:  npm run export-abi --workspace=@minga/shared
 */
const fs = require("fs");
const path = require("path");

const artifacts = path.join(__dirname, "..", "artifacts", "contracts");
const out = path.join(__dirname, "..", "..", "shared", "src", "abi.ts");

const targets = [
  ["ConservationAgreement.sol", "ConservationAgreement", "conservationAgreementAbi"],
  ["AgreementFactoryRegistry.sol", "AgreementFactoryRegistry", "agreementFactoryRegistryAbi"],
  ["MockUSD.sol", "MockUSD", "mockUsdAbi"],
];

let body =
  "// GENERATED by packages/contracts/scripts/export-abi.cjs from the compiled artifacts. Do not edit by hand.\n\n";
for (const [file, name, exportName] of targets) {
  const artifact = JSON.parse(fs.readFileSync(path.join(artifacts, file, `${name}.json`), "utf8"));
  body += `export const ${exportName} = ${JSON.stringify(artifact.abi, null, 2)} as const;\n\n`;
}
fs.writeFileSync(out, body);
console.log(`Wrote ${out} (${body.length} bytes)`);
